name: Usando expresiones

on: 
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'
  issues:
    types: 
      - labeled
  workflow_dispatch:
    inputs:
      edad:
        description: "edad del usuario"
        required: true
        type: number
      nombre:
        description: "nombre del usuario"
        required: true
        default: "Git"
        type: string

jobs:
  mayor:
    if: ${{ inputs.edad >= 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: correr script
        run: echo ${{inputs.nombre}} es adulto
      - name: correr python
        run: python main.py
  menor:
    if: ${{ inputs.edad < 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: correr script
        run: echo ${{inputs.nombre}} es menor de edad
      
